import { forwardRef } from 'react';
import { TrendingUp, TrendingDown, Wallet, Trophy, Target, Calendar } from 'lucide-react';
import type { ExportLanguage } from '@/pages/admin/trade-tracker/ExportPage';

interface AccountData {
  nickname: string;
  currency: string;
  initialBalance: number;
  thisWeekBalance: number;
  thisWeekNetProfit: number;
  thisWeekPercent: number;
  allTimeNetProfit: number;
  allTimePercent: number;
}

interface CombinedTotal {
  thisWeekBalance: number;
  thisWeekNetProfit: number;
  thisWeekPercent: number;
  allTimeNetProfit: number;
  allTimePercent: number;
}

type PeriodType = 'daily' | 'weekly' | 'monthly' | 'yearly' | 'all' | 'custom';

interface InfographicCanvasProps {
  accountsData: AccountData[];
  periodLabel: string;
  combinedTotal: CombinedTotal | null;
  language: ExportLanguage;
  periodType: PeriodType;
}

// Translation strings for each language with period-based labels
const getTranslations = (periodType: PeriodType) => {
  const periodLabels = {
    en: {
      daily: { balance: 'Today Balance', profit: 'Today Net Profit' },
      weekly: { balance: 'This Week Balance', profit: 'This Week Net Profit' },
      monthly: { balance: 'This Month Balance', profit: 'This Month Net Profit' },
      yearly: { balance: 'This Year Balance', profit: 'This Year Net Profit' },
      all: { balance: 'Current Balance', profit: 'Period Net Profit' },
      custom: { balance: 'Period Balance', profit: 'Period Net Profit' },
    },
    lo: {
      daily: { balance: 'ຍອດເງິນມື້ນີ້', profit: 'ກຳໄລສຸດທິມື້ນີ້' },
      weekly: { balance: 'ຍອດເງິນອາທິດນີ້', profit: 'ກຳໄລສຸດທິອາທິດນີ້' },
      monthly: { balance: 'ຍອດເງິນເດືອນນີ້', profit: 'ກຳໄລສຸດທິເດືອນນີ້' },
      yearly: { balance: 'ຍອດເງິນປີນີ້', profit: 'ກຳໄລສຸດທິປີນີ້' },
      all: { balance: 'ຍອດເງິນປັດຈຸບັນ', profit: 'ກຳໄລສຸດທິໄລຍະ' },
      custom: { balance: 'ຍອດເງິນໄລຍະ', profit: 'ກຳໄລສຸດທິໄລຍະ' },
    },
    th: {
      daily: { balance: 'ยอดเงินวันนี้', profit: 'กำไรสุทธิวันนี้' },
      weekly: { balance: 'ยอดเงินสัปดาห์นี้', profit: 'กำไรสุทธิสัปดาห์นี้' },
      monthly: { balance: 'ยอดเงินเดือนนี้', profit: 'กำไรสุทธิเดือนนี้' },
      yearly: { balance: 'ยอดเงินปีนี้', profit: 'กำไรสุทธิปีนี้' },
      all: { balance: 'ยอดเงินปัจจุบัน', profit: 'กำไรสุทธิช่วงเวลา' },
      custom: { balance: 'ยอดเงินช่วงเวลา', profit: 'กำไรสุทธิช่วงเวลา' },
    },
  };

  return {
    en: {
      title: 'Trade Tracker',
      subtitle: 'Trading Performance Report',
      periodBalance: periodLabels.en[periodType].balance,
      periodProfit: periodLabels.en[periodType].profit,
      allTimeProfit: 'All Time Net Profit',
      combinedTotal: 'Combined Total',
      generatedBy: 'Generated by Trade Tracker',
      fontFamily: 'Inter, system-ui, sans-serif',
    },
    lo: {
      title: 'ຕິດຕາມການຊື້ຂາຍ',
      subtitle: 'ລາຍງານຜົນການຊື້ຂາຍ',
      periodBalance: periodLabels.lo[periodType].balance,
      periodProfit: periodLabels.lo[periodType].profit,
      allTimeProfit: 'ກຳໄລສຸດທິທັງໝົດ',
      combinedTotal: 'ລວມທັງໝົດ',
      generatedBy: 'ສ້າງໂດຍ Trade Tracker',
      fontFamily: 'Phetsarath, sans-serif',
    },
    th: {
      title: 'ติดตามการซื้อขาย',
      subtitle: 'รายงานผลการซื้อขาย',
      periodBalance: periodLabels.th[periodType].balance,
      periodProfit: periodLabels.th[periodType].profit,
      allTimeProfit: 'กำไรสุทธิทั้งหมด',
      combinedTotal: 'รวมทั้งหมด',
      generatedBy: 'สร้างโดย Trade Tracker',
      fontFamily: 'Sarabun, Tahoma, sans-serif',
    },
  };
};

const InfographicCanvas = forwardRef<HTMLDivElement, InfographicCanvasProps>(
  ({ accountsData, periodLabel, combinedTotal, language, periodType }, ref) => {
    const translations = getTranslations(periodType);
    const t = translations[language];
    
    // Format currency - for Cents accounts, show value in cents format
    const formatCurrency = (amount: number, currency: string = 'USD') => {
      if (currency === 'Cents') {
        // Show cents with ¢ symbol for clarity
        return `¢${new Intl.NumberFormat('en-US', {
          minimumFractionDigits: 2,
          maximumFractionDigits: 2,
        }).format(amount)}`;
      }
      return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: currency,
        minimumFractionDigits: 2,
      }).format(amount);
    };

    const formatPercent = (percent: number) => {
      return `${percent >= 0 ? '+' : ''}${percent.toFixed(2)}%`;
    };

    return (
      <div
        ref={ref}
        className="p-8"
        style={{
          background: 'linear-gradient(145deg, #0f0f23 0%, #1a1a3e 35%, #0d1b2a 70%, #0a0a1a 100%)',
          fontFamily: t.fontFamily,
          position: 'relative',
          overflow: 'hidden',
          minWidth: '520px',
          maxWidth: '600px',
        }}
      >
        {/* Decorative background elements */}
        <div
          style={{
            position: 'absolute',
            top: '-50%',
            right: '-30%',
            width: '80%',
            height: '80%',
            background: 'radial-gradient(circle, rgba(245, 158, 11, 0.08) 0%, transparent 70%)',
            pointerEvents: 'none',
          }}
        />
        <div
          style={{
            position: 'absolute',
            bottom: '-30%',
            left: '-20%',
            width: '60%',
            height: '60%',
            background: 'radial-gradient(circle, rgba(59, 130, 246, 0.06) 0%, transparent 70%)',
            pointerEvents: 'none',
          }}
        />

        {/* Header */}
        <div className="text-center mb-8 relative">
          <div 
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-full mb-4"
            style={{
              background: 'linear-gradient(135deg, rgba(245, 158, 11, 0.2) 0%, rgba(251, 191, 36, 0.1) 100%)',
              border: '1px solid rgba(245, 158, 11, 0.3)',
              boxShadow: '0 4px 20px rgba(245, 158, 11, 0.15)',
            }}
          >
            <TrendingUp className="h-5 w-5" style={{ color: '#F59E0B' }} />
            <span className="text-lg font-bold" style={{ color: '#F59E0B' }}>
              {t.title}
            </span>
          </div>
          <h1 
            className="text-2xl font-bold mb-2"
            style={{ 
              color: '#ffffff',
              textShadow: '0 2px 10px rgba(0,0,0,0.3)',
            }}
          >
            {periodLabel}
          </h1>
          <p style={{ color: 'rgba(255, 255, 255, 0.5)', fontSize: '13px', letterSpacing: '1.5px' }}>
            {t.subtitle}
          </p>
        </div>

        {/* Accounts */}
        <div className="space-y-4 mb-6 relative">
          {accountsData.map((account, index) => (
            <div
              key={index}
              style={{
                background: 'rgba(255, 255, 255, 0.03)',
                backdropFilter: 'blur(10px)',
                borderRadius: '14px',
                padding: '20px',
                border: '1px solid rgba(255, 255, 255, 0.08)',
                boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
              }}
            >
              <div className="flex items-center gap-2.5 mb-4">
                <div
                  style={{
                    background: 'linear-gradient(135deg, rgba(59, 130, 246, 0.3) 0%, rgba(99, 102, 241, 0.2) 100%)',
                    padding: '8px',
                    borderRadius: '10px',
                    border: '1px solid rgba(59, 130, 246, 0.3)',
                  }}
                >
                  <Wallet className="h-4 w-4" style={{ color: '#60A5FA' }} />
                </div>
                <span className="text-base font-semibold" style={{ color: '#ffffff' }}>
                  {account.nickname}
                </span>
                <span 
                  className="text-xs px-2.5 py-1 rounded-full"
                  style={{ 
                    background: 'rgba(255, 255, 255, 0.1)',
                    color: 'rgba(255, 255, 255, 0.6)',
                  }}
                >
                  {account.currency}
                </span>
              </div>
              
              <div className="grid grid-cols-3 gap-4">
                <div>
                  <p style={{ color: 'rgba(255, 255, 255, 0.4)', fontSize: '11px', marginBottom: '6px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                    {t.periodBalance}
                  </p>
                  <p className="font-bold text-lg" style={{ color: '#ffffff' }}>
                    {formatCurrency(account.thisWeekBalance, account.currency)}
                  </p>
                </div>
                <div>
                  <p style={{ color: 'rgba(255, 255, 255, 0.4)', fontSize: '11px', marginBottom: '6px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                    {t.periodProfit}
                  </p>
                  <p 
                    className="font-bold text-lg flex items-center gap-1.5"
                    style={{ color: account.thisWeekNetProfit >= 0 ? '#22C55E' : '#EF4444' }}
                  >
                    {account.thisWeekNetProfit >= 0 ? (
                      <TrendingUp className="h-4 w-4" />
                    ) : (
                      <TrendingDown className="h-4 w-4" />
                    )}
                    {account.thisWeekNetProfit >= 0 ? '+' : ''}
                    {formatCurrency(account.thisWeekNetProfit, account.currency)}
                  </p>
                  <p style={{ color: account.thisWeekNetProfit >= 0 ? '#22C55E' : '#EF4444', fontSize: '12px' }}>
                    {formatPercent(account.thisWeekPercent)}
                  </p>
                </div>
                <div>
                  <p style={{ color: 'rgba(255, 255, 255, 0.4)', fontSize: '11px', marginBottom: '6px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                    {t.allTimeProfit}
                  </p>
                  <p 
                    className="font-bold text-lg"
                    style={{ color: account.allTimeNetProfit >= 0 ? '#22C55E' : '#EF4444' }}
                  >
                    {account.allTimeNetProfit >= 0 ? '+' : ''}
                    {formatCurrency(account.allTimeNetProfit, account.currency)}
                  </p>
                  <p style={{ color: account.allTimeNetProfit >= 0 ? '#22C55E' : '#EF4444', fontSize: '12px' }}>
                    {formatPercent(account.allTimePercent)}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Combined Total */}
        {combinedTotal && (
          <div
            style={{
              background: 'linear-gradient(135deg, rgba(245, 158, 11, 0.15) 0%, rgba(251, 191, 36, 0.08) 50%, rgba(245, 158, 11, 0.12) 100%)',
              backdropFilter: 'blur(10px)',
              borderRadius: '16px',
              padding: '20px',
              border: '1px solid rgba(245, 158, 11, 0.25)',
              boxShadow: '0 12px 40px rgba(245, 158, 11, 0.1), inset 0 1px 0 rgba(255, 255, 255, 0.1)',
            }}
          >
            <div className="flex items-center gap-2.5 mb-4">
              <div
                style={{
                  background: 'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)',
                  padding: '10px',
                  borderRadius: '12px',
                  boxShadow: '0 4px 15px rgba(245, 158, 11, 0.4)',
                }}
              >
                <Trophy className="h-5 w-5" style={{ color: '#ffffff' }} />
              </div>
              <span className="text-lg font-bold" style={{ color: '#F59E0B' }}>
                {t.combinedTotal}
              </span>
            </div>
            
            <div className="grid grid-cols-3 gap-4">
              <div>
                <p style={{ color: 'rgba(255, 255, 255, 0.5)', fontSize: '11px', marginBottom: '6px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                  {t.periodBalance}
                </p>
                <p className="font-bold text-xl" style={{ color: '#ffffff' }}>
                  ¢{new Intl.NumberFormat('en-US', { minimumFractionDigits: 2 }).format(combinedTotal.thisWeekBalance)}
                </p>
              </div>
              <div>
                <p style={{ color: 'rgba(255, 255, 255, 0.5)', fontSize: '11px', marginBottom: '6px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                  {t.periodProfit}
                </p>
                <p 
                  className="font-bold text-xl flex items-center gap-1.5"
                  style={{ color: combinedTotal.thisWeekNetProfit >= 0 ? '#22C55E' : '#EF4444' }}
                >
                  {combinedTotal.thisWeekNetProfit >= 0 ? (
                    <TrendingUp className="h-4 w-4" />
                  ) : (
                    <TrendingDown className="h-4 w-4" />
                  )}
                  {combinedTotal.thisWeekNetProfit >= 0 ? '+' : ''}
                  ¢{new Intl.NumberFormat('en-US', { minimumFractionDigits: 2 }).format(combinedTotal.thisWeekNetProfit)}
                </p>
                <p style={{ color: combinedTotal.thisWeekNetProfit >= 0 ? '#22C55E' : '#EF4444', fontSize: '12px' }}>
                  {formatPercent(combinedTotal.thisWeekPercent)}
                </p>
              </div>
              <div>
                <p style={{ color: 'rgba(255, 255, 255, 0.5)', fontSize: '11px', marginBottom: '6px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                  {t.allTimeProfit}
                </p>
                <p 
                  className="font-bold text-xl"
                  style={{ color: combinedTotal.allTimeNetProfit >= 0 ? '#22C55E' : '#EF4444' }}
                >
                  {combinedTotal.allTimeNetProfit >= 0 ? '+' : ''}
                  ¢{new Intl.NumberFormat('en-US', { minimumFractionDigits: 2 }).format(combinedTotal.allTimeNetProfit)}
                </p>
                <p style={{ color: combinedTotal.allTimeNetProfit >= 0 ? '#22C55E' : '#EF4444', fontSize: '12px' }}>
                  {formatPercent(combinedTotal.allTimePercent)}
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="mt-8 text-center relative">
          <div 
            style={{ 
              height: '1px', 
              background: 'linear-gradient(90deg, transparent 0%, rgba(255, 255, 255, 0.1) 50%, transparent 100%)',
              marginBottom: '12px',
            }} 
          />
          <p style={{ color: 'rgba(255, 255, 255, 0.3)', fontSize: '11px' }}>
            {t.generatedBy} • {new Date().toLocaleDateString('en-GB')}
          </p>
        </div>
      </div>
    );
  }
);

InfographicCanvas.displayName = 'InfographicCanvas';

export default InfographicCanvas;
